In [1]:
!pip install quandl

Collecting quandl
  Downloading Quandl-3.5.3-py2.py3-none-any.whl (25 kB)
Collecting inflection>=0.3.1
  Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from quandl) (1.15.0)
Requirement already satisfied: python-dateutil in c:\programdata\anaconda3\lib\site-packages (from quandl) (2.8.1)
Requirement already satisfied: numpy>=1.8 in c:\programdata\anaconda3\lib\site-packages (from quandl) (1.18.5)
Requirement already satisfied: pandas>=0.14 in c:\programdata\anaconda3\lib\site-packages (from quandl) (1.0.5)
Requirement already satisfied: requests>=2.7.0 in c:\programdata\anaconda3\lib\site-packages (from quandl) (2.24.0)
Requirement already satisfied: more-itertools in c:\programdata\anaconda3\lib\site-packages (from quandl) (8.4.0)
Requirement already satisfied: pytz>=2017.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.14->quandl) (2020.1)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (2.10)
Installing collected packages: inflection, quandl
Successfully installed inflection-0.5.1 quandl-3.5.3

In [3]:
import quandl
quandl.ApiConfig.api_key = 'NEAwokdYQQH8a-bxsNmF'

In [5]:
df = quandl.get("EOD/AAPL")

In [6]:
df

,Open,High,Low,Close,Volume,Dividend,Split,Adj_Open,Adj_High,Adj_Low,Adj_Close,Adj_Volume
Date,,,,,,,,,,,,
2013-09-03,493.10,500.600,487.350,488.580,11854600.0,0.0,1.0,15.619650,15.857223,15.437510,15.476472,331928800.0
2013-09-04,499.56,502.240,496.280,498.691,12322600.0,0.0,1.0,15.824280,15.909173,15.720381,15.796753,345032800.0
2013-09-05,500.25,500.680,493.640,495.270,8441700.0,0.0,1.0,15.846136,15.859757,15.636755,15.688388,236367600.0
2013-09-06,498.44,499.380,489.950,498.220,12840200.0,0.0,1.0,15.788802,15.818578,15.519869,15.781833,359525600.0
2013-09-09,505.00,507.920,503.480,506.170,12167400.0,0.0,1.0,15.996600,16.089095,15.948451,16.033661,340687200.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2017-12-21,174.17,176.020,174.100,175.010,20949896.0,0.0,1.0,41.899570,42.344619,41.882730,42.101646,83799584.0
2017-12-22,174.68,175.424,174.500,175.010,16349444.0,0.0,1.0,42.022259,42.201241,41.978957,42.101646,65397776.0
2017-12-26,170.80,171.470,169.679,170.570,33185536.0,0.0,1.0,41.088858,41.250038,40.819183,41.033528,132742144.0
2017-12-27,170.10,170.780,169.710,170.600,21498213.0,0.0,1.0,40.920461,41.084047,40.826640,41.040745,85992852.0
2017-12-28,171.00,171.850,170.480,171.080,16480187.0,0.0,1.0,41.136972,41.341454,41.011877,41.156217,65920748.0

In [7]:
df['HL_PCT'] = (df['Adj_High']-df['Adj_Low'])/df['Adj_Close']*100

In [8]:
df['HL_PCT']

Date
2013-09-03    2.711941
2013-09-04    1.195129
2013-09-05    1.421447
2013-09-06    1.892738
2013-09-09    0.877176
                ...
2017-12-21    1.097080
2017-12-22    0.527970
2017-12-26    1.050009
2017-12-27    0.627198
2017-12-28    0.800795
Name: HL_PCT, Length: 1090, dtype: float64

In [9]:
df['PCT_change'] = (df['Adj_Close']-df['Adj_Open'])/df['Adj_Open']*100
df['PCT_change']

Date
2013-09-03   -0.916650
2013-09-04   -0.173953
2013-09-05   -0.995502
2013-09-06   -0.044138
2013-09-09    0.231683
                ...
2017-12-21    0.482287
2017-12-22    0.188917
2017-12-26   -0.134660
2017-12-27    0.293945
2017-12-28    0.046784
Name: PCT_change, Length: 1090, dtype: float64

In [10]:
import pandas as pd
import numpy as np
import math

In [11]:
data = (df['Adj_Close'],df['PCT_change'],df['HL_PCT'],df['Adj_Volume'])
df1 = pd.DataFrame(data)

In [12]:
df1

Date,2013-09-03,2013-09-04,2013-09-05,2013-09-06,2013-09-09,2013-09-10,2013-09-11,2013-09-12,2013-09-13,2013-09-16,...,2017-12-14,2017-12-15,2017-12-18,2017-12-19,2017-12-20,2017-12-21,2017-12-22,2017-12-26,2017-12-27,2017-12-28
Adj_Close,1.547647e+01,1.579675e+01,1.568839e+01,1.578183e+01,1.603366e+01,1.566843e+01,1.481539e+01,1.497313e+01,1.472637e+01,1.425820e+01,...,4.143046e+01,4.185146e+01,4.244085e+01,4.198858e+01,4.194287e+01,4.210165e+01,4.210165e+01,4.103353e+01,4.104075e+01,4.115622e+01
PCT_change,-9.166498e-01,-1.739531e-01,-9.955022e-01,-4.413771e-02,2.316832e-01,-2.283682e+00,1.498683e-01,8.943436e-01,-9.460515e-01,-2.360087e+00,...,-1.044084e-01,1.958187e-01,8.806038e-01,-2.799520e-01,-2.973638e-01,4.822874e-01,1.889169e-01,-1.346604e-01,2.939447e-01,4.678363e-02
HL_PCT,2.711941e+00,1.195129e+00,1.421447e+00,1.892738e+00,8.771757e-01,3.628902e+00,1.898612e+00,1.986503e+00,1.533491e+00,3.196903e+00,...,8.593659e-01,9.829281e-01,1.326380e+00,7.448149e-01,1.244623e+00,1.097080e+00,5.279698e-01,1.050009e+00,6.271981e-01,8.007949e-01
Adj_Volume,3.319288e+08,3.450328e+08,2.363676e+08,3.595256e+08,3.406872e+08,7.431956e+08,8.986964e+08,4.040512e+08,2.988356e+08,5.437068e+08,...,8.190616e+07,1.606772e+08,1.176845e+08,1.097458e+08,9.390260e+07,8.379958e+07,6.539778e+07,1.327421e+08,8.599285e+07,6.592075e+07

In [13]:
df1.isna().sum()

Date
2013-09-03    0
2013-09-04    0
2013-09-05    0
2013-09-06    0
2013-09-09    0
             ..
2017-12-21    0
2017-12-22    0
2017-12-26    0
2017-12-27    0
2017-12-28    0
Length: 1090, dtype: int64

In [18]:
df1.fillna(-99999)

Date,2013-09-03,2013-09-04,2013-09-05,2013-09-06,2013-09-09,2013-09-10,2013-09-11,2013-09-12,2013-09-13,2013-09-16,...,2017-12-14,2017-12-15,2017-12-18,2017-12-19,2017-12-20,2017-12-21,2017-12-22,2017-12-26,2017-12-27,2017-12-28
Adj_Close,1.547647e+01,1.579675e+01,1.568839e+01,1.578183e+01,1.603366e+01,1.566843e+01,1.481539e+01,1.497313e+01,1.472637e+01,1.425820e+01,...,4.143046e+01,4.185146e+01,4.244085e+01,4.198858e+01,4.194287e+01,4.210165e+01,4.210165e+01,4.103353e+01,4.104075e+01,4.115622e+01
PCT_change,-9.166498e-01,-1.739531e-01,-9.955022e-01,-4.413771e-02,2.316832e-01,-2.283682e+00,1.498683e-01,8.943436e-01,-9.460515e-01,-2.360087e+00,...,-1.044084e-01,1.958187e-01,8.806038e-01,-2.799520e-01,-2.973638e-01,4.822874e-01,1.889169e-01,-1.346604e-01,2.939447e-01,4.678363e-02
HL_PCT,2.711941e+00,1.195129e+00,1.421447e+00,1.892738e+00,8.771757e-01,3.628902e+00,1.898612e+00,1.986503e+00,1.533491e+00,3.196903e+00,...,8.593659e-01,9.829281e-01,1.326380e+00,7.448149e-01,1.244623e+00,1.097080e+00,5.279698e-01,1.050009e+00,6.271981e-01,8.007949e-01
Adj_Volume,3.319288e+08,3.450328e+08,2.363676e+08,3.595256e+08,3.406872e+08,7.431956e+08,8.986964e+08,4.040512e+08,2.988356e+08,5.437068e+08,...,8.190616e+07,1.606772e+08,1.176845e+08,1.097458e+08,9.390260e+07,8.379958e+07,6.539778e+07,1.327421e+08,8.599285e+07,6.592075e+07

In [19]:
df2 = df1.transpose()
df2

            Adj_Close  PCT_change    HL_PCT   Adj_Volume
Date
2013-09-03  15.476472   -0.916650  2.711941  331928800.0
2013-09-04  15.796753   -0.173953  1.195129  345032800.0
2013-09-05  15.688388   -0.995502  1.421447  236367600.0
2013-09-06  15.781833   -0.044138  1.892738  359525600.0
2013-09-09  16.033661    0.231683  0.877176  340687200.0
...               ...         ...       ...          ...
2017-12-21  42.101646    0.482287  1.097080   83799584.0
2017-12-22  42.101646    0.188917  0.527970   65397776.0
2017-12-26  41.033528   -0.134660  1.050009  132742144.0
2017-12-27  41.040745    0.293945  0.627198   85992852.0
2017-12-28  41.156217    0.046784  0.800795   65920748.0

[1090 rows x 4 columns]

In [20]:
x = df2[['PCT_change','HL_PCT','Adj_Volume']].values
y = df2['Adj_Close'].values

In [21]:
from sklearn import linear_model 
from sklearn.linear_model import LinearRegression

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [23]:
regressor = LinearRegression()  
regressor.fit(x_train, y_train)

LinearRegression()

In [24]:
print(regressor.coef_)

[-8.83958597e-02  1.27365006e+00 -3.96145230e-08]

In [26]:
y_prediction = regressor.predict(x_test)

In [27]:
y_prediction

array([25.9622624 , 25.72492922, 28.84863339, 26.07430453, 26.52067036,
       19.55596983, 22.17182154, 28.43326035, 27.29448068, 27.00620742,
       29.2048409 , 29.3399241 , 22.41454736, 29.39998584, 28.73872097,
       28.72243245, 12.2809246 , 27.05454366, 22.93904986, 22.94956153,
       28.54511977, 26.34327485, 28.59279596, 29.48658366, 24.73906379,
       27.39536606, 28.45324696, 28.07102439, 23.48102021, 28.67632797,
       28.1947993 , 19.91174346, 24.63000709, 28.27541258, 30.95131929,
       27.45321189, 22.67499908, 27.31714517, 28.75615547, 28.43891282,
       26.59891603, 28.32444176, 29.27628293, 17.36717213, 25.12180751,
       28.36559793, 29.68082522, 24.4734577 , 20.92960341, 28.56730781,
       30.04678913, 24.42614941, 24.87959583, 27.38610456, 27.0396278 ,
       30.59745122, 27.15378748, 28.91790251, 20.18635124, 26.53542252,
       27.23707908, 28.29707453,  5.41074794, 26.10003513, 26.3963417 ,
       16.83122422, 28.15729389, 29.70132648, 26.35414129, 30.15209782,
       24.5472611 , 29.4511675 , 26.10383827, 26.37999612, 29.42824157,
       23.81647772, 19.6584749 , 29.0724107 , 26.39470584, 26.30944708,
       25.63019565, 27.14878576, 27.98433796, 29.32954635, 27.69210079,
       29.58991816, 29.87965811, 27.74709504, 24.98365216, 28.29792945,
       30.4376319 , 27.5332954 , 30.04245454, 29.67241496, 29.56447488,
       21.276846  , 29.74670881, 27.13919129, 28.51968565, 25.4494272 ,
       24.82959866, 28.22514805, 28.63713201, 28.60302582, 29.43166991,
       27.69594058,  7.45667051, 27.61459055, 29.12125376, 30.02962102,
       19.45125789, 27.70486413, 29.16020086, 30.16331589, 27.34476962,
       24.30273246, 25.75420452, 27.24767712, 24.5501233 , 25.41421123,
       27.39403029, 29.18356417, 29.67531344, 30.25669914, 20.13549249,
       29.45404687, 28.70329098, 22.69477537, 27.40005155, 24.12070288,
       29.57131754, 26.28753303, 30.65425926, 18.91604676, 26.27844254,
       22.63903567, 30.30163018, 17.2716947 , 22.72300044, 28.24112785,
       27.87747814, 26.75824833, 22.41568712, 23.8442138 , 16.01849916,
       21.80516253, 30.01843921, 28.93500478, 27.41234734, 29.11912417,
       28.82669779, 29.82388615, 30.30965253, 29.21271736, 29.32602619,
       26.3896092 , 27.36522064, 28.05779703, 27.46344562, 29.34855423,
       29.84459319, 24.57090696,  7.17171193, 28.78053165, 15.38082621,
       24.32406649, 26.31404535, 24.7716539 , 23.57285957, 26.98675329,
       25.9163279 , 28.64971357, 28.71718451, 21.96028172, 29.97770157,
       28.85839609, 28.41508518, 27.96053222, 28.23303888, 23.80025087,
       28.69871407, 28.82897874, 30.59292184, 30.43080847, 23.7357084 ,
       26.06894541, 28.51446154, 26.26458992, 29.50735838, 24.90540682,
       29.24220143, 28.96276633, 29.3816079 , 26.14153261, 27.74617619,
       30.14466562, 30.44802688, 18.71710616, 22.53369572, 26.98151092,
       29.4697477 , 29.22012043, 26.86449237, 24.78601439, 28.47059508,
       28.91901338, 29.30122651, 24.09128965, 29.27047817, 28.67549966,
       22.16162941, 28.87138915, 28.42908001, 25.69541816, 18.63091492,
       28.1010454 , 28.41593725, 23.71151866])

In [28]:
from sklearn import metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [29]:
r2 = r2_score(y_test,y_prediction)
print('r2 score for perfect model is',r2)

r2 score for perfect model is 0.2808695083761985

In [30]:
print('Mean Square Error:', metrics.mean_squared_error(y_test, y_prediction))

Mean Square Error: 31.18360398392956